name: Create AWS AppFlow

on:
  push:
    branches:
      - main

jobs:
  create_appflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version  # Verify installation

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-2

      - name: Create AWS AppFlow
        run: |
          aws appflow create-flow \
            --flow-name "SalesforceToS3Flow" \
            --description "Sync Salesforce data to S3" \
            --source-flow-config '{
              "connectorType": "Salesforce",
              "sourceConnectorProperties": {
                "Salesforce": {
                  "object": "Account"
                }
              },
              "connectorProfileName": "Test-Connection"
            }' \
            --destination-flow-config-list '[
              {
                "connectorType": "S3",
                "destinationConnectorProperties": {
                  "S3": {
                    "bucketName": "sfbucket786",
                    "s3OutputFormatConfig": {
                      "fileType": "CSV"
                    }
                  }
                }
              }
            ]' \
            --trigger-config '{ "triggerType": "OnDemand" }' \
            --tasks '[
              {
                "sourceFields": ["CaseNumber"],
                "destinationField": "CaseNumber",
                "taskType": "Map"
              }
            ]'
